# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmlore < Formula
  desc "Discover and curate LLM/agent learning repositories from a local HTML dashboard"
  homepage "https://github.com/csthink/llmlore"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.0/llmlore_0.1.0_darwin_amd64.tar.gz"
      sha256 "65c6e6d2715f0cf93d5da9fa67c92c2a78801f08d0b15428c222ba6db798dfe8"

      define_method(:install) do
        bin.install "llmlore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.0/llmlore_0.1.0_darwin_arm64.tar.gz"
      sha256 "7e945d42dc9467ec59d31fae3714b26d567ac597d139f7af89b2102d5841309c"

      define_method(:install) do
        bin.install "llmlore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.0/llmlore_0.1.0_linux_amd64.tar.gz"
      sha256 "1232b54b6f873e2fbcd0ec616f2899904102815d67c6e3d1450b53e585ff8296"
      define_method(:install) do
        bin.install "llmlore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.0/llmlore_0.1.0_linux_arm64.tar.gz"
      sha256 "fccf4e660eb98470fb8b3b77532d85d61c5436a596333261d846f85339b08ed2"
      define_method(:install) do
        bin.install "llmlore"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        llmlore pull     # download the pre-generated open dataset (no key needed)
        llmlore          # render + serve the dashboard, opens your browser

      The open dataset is bundled with each release; `llmlore pull` refreshes it.
      To regenerate locally, set LLMLORE_LLM_API_KEY and run `llmlore update`.
      Personal star data stays local in ~/.local/share/llmlore/ and is never shared.
    EOS
  end

  test do
    system "#{bin}/llmlore", "--help"
  end
end
