# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmlore < Formula
  desc "Discover and curate LLM/agent learning repositories from a local HTML dashboard"
  homepage "https://github.com/csthink/llmlore"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.1/llmlore_0.1.1_darwin_amd64.tar.gz"
      sha256 "fca9fd743d5d23264383d772efa51950c1926d7b75fa4fc48261616f75d2b142"

      define_method(:install) do
        bin.install "llmlore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.1/llmlore_0.1.1_darwin_arm64.tar.gz"
      sha256 "83fe45a5e3b554733af67d855e1141d63b99ce540bf59f6f7e84d97f324cae0b"

      define_method(:install) do
        bin.install "llmlore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.1/llmlore_0.1.1_linux_amd64.tar.gz"
      sha256 "ed8e22bd58d9d59e221de72f662f721248c0e46a3fa72afe7a7947d8c8fb64c4"
      define_method(:install) do
        bin.install "llmlore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/csthink/llmlore/releases/download/v0.1.1/llmlore_0.1.1_linux_arm64.tar.gz"
      sha256 "99789bd774af54f420fe71d2d45a1158011f989ccf3a28885161fedd9731bdaa"
      define_method(:install) do
        bin.install "llmlore"
      end
    end
  end

  def caveats
    <<~EOS
      Get started:
        llmlore pull     # download the pre-generated open dataset (no key needed)
        llmlore          # render + serve the dashboard, opens your browser

      The open dataset is bundled with each release; `llmlore pull` refreshes it.
      To regenerate locally, set LLMLORE_LLM_API_KEY and run `llmlore update`.
      Personal star data stays local in ~/.local/share/llmlore/ and is never shared.
    EOS
  end

  test do
    system "#{bin}/llmlore", "--help"
  end
end
